"""Reviewed additive counter-window contract shared with the DAP source.

Expected decisions are authored, not generated by the implementation under test.
This is an interface probe, not a Dragapult strategy or a prize planner.
"""
from __future__ import annotations

import copy
import hashlib
import re


COUNTER_KEYS = ("target_pending_damage_counters", "remaining_damage_counters")


def counter_cases(sample_policy, option, frame):
    policy = sample_policy()
    policy["count_rules"] = []
    goal = policy["goals"][0]["goal_id"]
    condition = lambda fact, op, value: {"fact": fact, "op": op, "value": value, "card_uid": None}
    # Prefer entity 51 while it needs its first counter and two remain.
    # Once paid (or only one remains), prefer entity 52. Never retain indexes.
    rule = lambda name, score, when: {
        "rule_id": name, "goal_id": goal, "goal_stage": "execute",
        "channel": "interaction", "horizon": 0, "confidence_milli": 1000,
        "base_score": score, "when": when, "score_terms": [],
    }
    policy["rules"] = [
        rule("counter.fallback-target", 100, [condition("option.target_entity_serial", "eq", 52)]),
        rule("counter.unpaid-target", 200, [
            condition("option.target_entity_serial", "eq", 51),
            condition("option.target_pending_damage_counters", "eq", 0),
            condition("option.remaining_damage_counters", "gte", 2),
        ]),
    ]
    initial = frame([
        option(i, kind="assignment_source", card_uid="M2_002", target_uid="M2_002",
               target_entity_serial=51+i, target_remaining_hp=70,
               target_pending_damage_counters=0, remaining_damage_counters=2)
        for i in range(2)
    ], "assignment_source", 1, 1, select_context_raw=14)
    cases = []

    def add(name, value, selected=None, error=""):
        cases.append({"case_id": "public-counter-" + name, "operation": "decide",
                      "policy": copy.deepcopy(policy), "allowed_card_uids": ["SVI_003", "M2_001", "M2_002"],
                      "frame": copy.deepcopy(value), "expected": {
                          "accepted": not error, "error_code": error,
                          "selected_indexes": selected if selected is not None else [],
                      }})

    add("initial", initial, [0])
    paid = copy.deepcopy(initial)
    paid["options"][0][COUNTER_KEYS[0]] = 1
    add("assigned-only-flip", paid, [1])
    last = copy.deepcopy(initial)
    for item in last["options"]:
        item[COUNTER_KEYS[1]] = 1
    add("remaining-only-flip", last, [1])
    moved = copy.deepcopy(initial)
    moved["options"].reverse()
    for i, item in enumerate(moved["options"]):
        item["index"] = i
    add("reordered", moved, [1])
    legacy = copy.deepcopy(initial)
    for item in legacy["options"]:
        for key in COUNTER_KEYS:
            del item[key]
    add("legacy-absent", legacy, [1])
    damage = copy.deepcopy(initial)
    damage["select_semantics"]["select_context_raw"] = 13
    add("damage-counter-context", damage, [0])
    maximum = copy.deepcopy(initial)
    for item in maximum["options"]:
        item.update(target_pending_damage_counters=100, remaining_damage_counters=100)
    add("bounded-maximum", maximum, [1])

    for name, mutate in [
        ("missing-peer", lambda f: f["options"][0].pop(COUNTER_KEYS[0])),
        ("missing-option", lambda f: [f["options"][1].pop(k) for k in COUNTER_KEYS]),
        ("wrong-context", lambda f: f["select_semantics"].update(select_context_raw=40)),
        ("wrong-type", lambda f: f["select_semantics"].update(select_type_raw=0)),
        ("budget-disagreement", lambda f: f["options"][1].update(remaining_damage_counters=1)),
        ("missing-identity", lambda f: f["options"][0].pop("target_entity_serial")),
        ("null-identity", lambda f: f["options"][0].update(target_entity_serial=None)),
        ("zero-identity", lambda f: f["options"][0].update(target_entity_serial=0)),
        ("unknown-field", lambda f: f["options"][0].update(counter_estimate=1)),
        ("malformed-option", lambda f: f["options"].__setitem__(1, None)),
    ]:
        bad = copy.deepcopy(initial)
        mutate(bad)
        add(name, bad, error="invalid_public_frame")
    for key in COUNTER_KEYS:
        for name, value in [("negative", -1), ("excess", 101), ("bool", True), ("string", "1"), ("null", None)]:
            bad = copy.deepcopy(initial)
            bad["options"][0][key] = value
            add(key + "-" + name, bad, error="invalid_public_frame")
    private = copy.deepcopy(initial)
    private["deck_order"] = ["M2_001"]
    add("hidden-field", private, error="private_or_runtime_frame")
    for value in (False, True, 1):
        compatible = copy.deepcopy(initial)
        compatible["public_state"]["self"]["active"][0]["appeared_this_turn"] = value
        add("public-appearance-" + str(value).lower(), compatible,
            [0] if type(value) is bool else None,
            "" if type(value) is bool else "invalid_public_frame")
    return cases


def extend_counter_contract(documents, sample_policy, option, frame):
    public_frame = documents["schema"]["$defs"]["public_frame"]
    option_schema = public_frame["properties"]["options"]["items"]
    for key in COUNTER_KEYS:
        option_schema["properties"][key] = {"type": "integer", "minimum": 0, "maximum": 100}
    # Optional for older frames; all-or-none across the entire current window.
    public_frame.setdefault("allOf", []).append({
        "if": {"properties": {"options": {"contains": {"anyOf": [{"required": [key]} for key in COUNTER_KEYS]}}}},
        "then": {"properties": {
            "options": {"items": {"required": [*COUNTER_KEYS, "target_entity_serial"], "properties": {
                "target_entity_serial": {"type": "integer", "minimum": 1, "maximum": 9007199254740991}}}},
            "select_semantics": {"properties": {"select_type_raw": {"const": 1}, "select_context_raw": {"enum": [13, 14]}}},
        }},
    })
    documents["profile"]["public_counter_state"] = {
        "version": 1, "optional_legacy_compatible": True,
        "contexts": [13, 14], "select_type_raw": 1, "range": [0, 100],
        "target_pending_damage_counters": "Accepted, uncommitted counters on this target entity in the current distribution.",
        "remaining_damage_counters": "Total unassigned counter budget before the current choice; equal on all options, including partial movement windows.",
        "invariants": ["Both fields on every option or neither on any option.", "Actual target_remaining_hp is unchanged until engine settlement.", "pending_assignment_count retains energy-assignment semantics.", "Reobserve after every choice; no inferred counters from sequence or old indexes.", "Counts only; engine target objects never cross the public boundary."],
    }
    documents["vectors"]["cases"].extend(counter_cases(sample_policy, option, frame))


def sync_consumer_pins(root, documents, canonical_bytes, *, check):
    """Regenerate only this reviewed contract's pins; never relax validation."""
    hashes = {key: hashlib.sha256(canonical_bytes(value)).hexdigest().upper()
              for key, value in documents.items()}
    for relative in ("scripts/ai/ptcgdap/author_strategy_package.py",
                     "scripts/ai/ptcgdap/packages/AuthorStrategyPackageLoader.gd"):
        path = root / relative
        # The standalone SDK has no GDScript loader.
        if not path.exists() and path.suffix == ".gd":
            continue
        source = path.read_text(encoding="utf-8")
        expected, count = re.subn(
            r'(COMPETITIVE_POLICY_V2_EXPECTED_BUNDLE_CANONICAL_SHA256\s*:?=\s*")[A-F0-9]{64}("\s*\n)',
            lambda m: m[1] + hashes["bundle"] + m[2], source)
        if count != 1:
            raise ValueError("counter contract consumer bundle pin missing: " + relative)
        pattern = r'(COMPETITIVE_POLICY_V2_EXPECTED_ARTIFACT_CANONICAL_SHA256\s*:?=\s*\{)(.*?)(\n\})'
        def replace_artifacts(match):
            body = match[2]
            for key in ("schema", "profile", "vectors"):
                body, n = re.subn(r'("' + key + r'":\s*")[A-F0-9]{64}(\")',
                                  lambda m: m[1] + hashes[key] + m[2], body)
                if n != 1:
                    raise ValueError("counter contract artifact pin missing: " + key)
            return match[1] + body + match[3]
        expected, count = re.subn(pattern, replace_artifacts, expected, flags=re.DOTALL)
        if count != 1:
            raise ValueError("counter contract consumer artifacts missing: " + relative)
        if check:
            if source != expected:
                raise SystemExit("contract consumer pin drift: " + relative)
        elif source != expected:
            path.write_text(expected, encoding="utf-8", newline="\n")
